<?xml version="1.0"?>
<!--
/*********************************************************************
* Copyright (c) 2024 Contributors to the Eclipse Foundation.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.daanse</groupId>
    <artifactId>org.eclipse.daanse.cwm.model</artifactId>
    <version>${revision}</version>
  </parent>
  <artifactId>org.eclipse.daanse.cwm.model.cwmx</artifactId>
  <packaging>pom</packaging>
  <name>Daanse CWM Extensions (CWMX)</name>

  <modules>
    <module>foundation.er</module>
    <module>resource.cobol</module>
    <module>resource.dmsii</module>
    <module>resource.ims</module>
    <module>resource.essbase</module>
    <module>resource.express</module>
    <module>analysis.informationset</module>
    <module>analysis.informationreporting</module>
  </modules>

</project>
