<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="express" nsURI="http://www.omg.org/spec/CWMX/1.1/resource/express"
    nsPrefix="express">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
    <details key="hiddenOpposites" value="true"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.eclipse.daanse.cwm.model.cwmx.resource"/>
    <details key="prefix" value="Express"/>
    <details key="oSGiCompatible" value="true"/>
    <details key="literalsInterface" value="true"/>
    <details key="loadInitialization" value="false"/>
    <details key="copyrightText" value="Copyright (c) 2025 Contributors to the Eclipse Foundation.&#xA;&#xA;This program and the accompanying materials are made&#xA;available under the terms of the Eclipse Public License 2.0&#xA;which is available at https://www.eclipse.org/legal/epl-2.0/&#xA;&#xA;SPDX-License-Identifier: EPL-2.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AggMap" eSuperTypes="http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Class">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents an Express aggregation map."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggMapComponent" ordered="false"
        upperBound="-1" eType="#//AggMapComponent" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies the AggMapComponents that constitute the AggMap."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggMapComponent" eSuperTypes="http://www.omg.org/spec/CWM/1.1/objectmodel/core#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a component of an Express aggregation map."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" lowerBound="1"
        eType="#//Dimension">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="aggMapComponent"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="aggMapComponent"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies the Dimension associated with the AggMapComponent."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" eType="#//Relation">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="aggMapComponent"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="aggMapComponent"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies the Relation used by the AggMapComponent."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggMap" lowerBound="1"
        eType="#//AggMap">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies the AggMap that includes the AggMapComponent."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computeClause" eType="#//PreComputeClause"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies a PreComputeClause associated with the AggMapComponent."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggOperator" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A text expression indicating the type of aggregate operation."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AliasDimension" eSuperTypes="#//Dimension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents an Express alias dimension."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseDimension" lowerBound="1"
        eType="#//SimpleDimension">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies the SimpleDimension for which this is an alias."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//Dimension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express composite."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="searchAlgorithm" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates the type of algorithm Express should use for loading and accessing the values of the Composite Dimension. The valid values are HASH, BTREE."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageSpace" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If specified, this defines the type of page space to be allocated to data relating specific values of the Composite to values of its base Dimensions:&#xA;&#xA;    OWNSPACE specifies that the data will be stored in private page space.&#xA;    SHAREDSPACE specifies that the data will be stored in the databases global page space."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conjoint" eSuperTypes="#//Dimension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express conjoint. This is a type of physical dimension that may be used to provide more efficient storage for sparse cubes."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="searchAlgorithm" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates the type of algorithm Express should use for loading and accessing the values of the Conjoint Dimension. Valid values are HASH, BTREE, NOHASH."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageSpace" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If specified, this defines the type of page space to be allocated to data relating specific values of the Conjoint to values of its base Dimensions:&#xA;&#xA;    OWNSPACE specifies that the data will be stored in private page space.&#xA;    SHAREDSPACE specifies that the data will be stored in the databases global page space."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Database" eSuperTypes="http://www.omg.org/spec/CWM/1.1/resource/multidimensional#//Schema">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express database."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension" abstract="true" eSuperTypes="http://www.omg.org/spec/CWM/1.1/resource/multidimensional#//Dimension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express dimension."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Formula" eSuperTypes="http://www.omg.org/spec/CWM/1.1/resource/multidimensional#//DimensionedObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express formula."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The calculation to be performed to produce values when you use the Formula. It can be any valid Express expression, including a constant or the name of a Variable."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="http://www.omg.org/spec/CWM/1.1/foundation/softwaredeployment#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An Express representation of the content of the Model."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreComputeClause" eSuperTypes="http://www.omg.org/spec/CWM/1.1/objectmodel/core#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a pre-compute clause for an Express aggregation map."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggMapComponent" lowerBound="1"
        eType="#//AggMapComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies the AggMapComponent to which the PreComputeClause relates."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusList" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Any">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The status of the dimension to aggregate."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program" eSuperTypes="http://www.omg.org/spec/CWM/1.1/foundation/softwaredeployment#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express program. The interface to the Program may be documented as an Operation associated with the Program."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="program" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An Express representation of the Program."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnDimension" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If present, this specifies that when the Program is called as a function it returns a value of the named Dimension."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="http://www.omg.org/spec/CWM/1.1/resource/multidimensional#//DimensionedObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a reference from one or more Dimensions to another Dimension."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDimension" lowerBound="1"
        eType="#//Dimension">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="relation"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="relation"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies the Dimension referenced by the Relation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTemp" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If set, this indicates that values of the Relation are only temporary, and will be discarded at the end of each Express session."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageSpace" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This identifies the type of page space in which data associated with the Relation will be stored:&#xA;&#xA;    OWNSPACE specifies that the data will be stored in private page space associated with the Relation.&#xA;    SHAREDSPACE specifies that the data will be stored in the databases global page space."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleDimension" eSuperTypes="#//Dimension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents an Express simple dimension."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aliasDimension" ordered="false"
        upperBound="-1" eType="#//AliasDimension">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies any AliasDimensions associated with the SimpleDimension."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="ecore:EClass http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Classifier">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="simpleDimension"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="simpleDimension"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies the SimpleDimensions data type."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Integer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If specified, this defines a fixed width, in bytes, for the storage area for each value of the SimpleDimension. Fixed widths can be specified for TEXT dimensions only. Valid width values are 1 through 256."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTime" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If set, indicates that the SimpleDimension is a time dimension."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Integer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This may be used for SimpleDimensions whose data type is WEEK or MONTH, to define time periods that span a multiple number of weeks or months.  With the WEEK data type, multiple can be an integer from 2 to 52. With the MONTH data type, multiple can be 2, 3, 4, or 6."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beginningPhase" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This may be used for any time data type except DAY, to specify the beginning phase of the Dimension.&#xA;For single weeks, beginningPhase can be a day of the week or a date. For multiple weeks, beginningPhase must be a date. For months, quarters, or years, beginningPhase must be a month, expressed as a month name or as a date."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endingPhase" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This may be used for any time data type except DAY, to specify the ending phase of the Dimension. For single weeks, endingPhase can be a day of the week or a date. For multiple weeks, endingPhase must be a date. For months, quarters, or years, endingPhase must be a month, expressed as a month name or as a date."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="searchAlgorithm" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates the type of algorithm Express should use for loading and accessing the values of the SimpleDimension. The valid values are HASH, BTREE."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageSpace" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If specified, this defines the type of page space to be allocated to values of the SimpleDimension:&#xA;&#xA;    OWNSPACE specifies that the data will be stored in private page space.&#xA;    SHAREDSPACE specifies that the data will be stored in the databases global page space."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSet" eSuperTypes="http://www.omg.org/spec/CWM/1.1/resource/multidimensional#//DimensionedObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express value set."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDimension" lowerBound="1"
        eType="#//Dimension">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="valueSet"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="valueSet"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies the Dimension whose values are to be stored in the ValueSet."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTemp" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If set, this indicates that values in the ValueSet are only temporary, and will be discarded at the end of each Express session."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="http://www.omg.org/spec/CWM/1.1/resource/multidimensional#//DimensionedObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express variable."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageType" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The type of storage to use for the Variable. The valid values are: TEMP, INPLACE, PERMANENT."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageSpace" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If specified, this defines the type of page space in which data associated with the Variable will be stored:&#xA;&#xA;    OWNSPACE specifies that the data will be stored in private page space associated with the Variable.&#xA;    SHAREDSPACE specifies that the data will be stored in the databases global page space."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Integer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If specified, this defines a fixed width, in bytes, for the storage area for each value of a Variable. Fixed widths can be specified only for dimensioned TEXT and INTEGER Variables."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Worksheet" eSuperTypes="http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Class">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represents a physical Express worksheet."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnDimension" eType="#//Dimension">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="columnDimensionInWorksheet"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="columnDimensionInWorksheet"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies a Dimension used as the column dimension of the Worksheet."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowDimension" eType="#//Dimension">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="rowDimensionInWorksheet"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="rowDimensionInWorksheet"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifies a Dimension used as the row dimension of the Worksheet."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTemp" eType="ecore:EDataType http://www.omg.org/spec/CWM/1.1/objectmodel/core#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If set, this indicates that values in the Worksheet are only temporary, and will be discarded at the end of each Express session."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
